### ISSUE TITLE
npm install broken with "typings not recognised as internal or external command"

### ISSUE THREAD

**Issue by NickIliev** [peoplewareDo/generator-nativescript-plugin#4]
Steps to reproduce:

```
npm i -g yo
npm i -g generator-nativescript-plugin
```

Throws with `typings not recognized as an internal or external command` perhaps because of using obsolete typings tool.

**Comment by victorsosa** [comment]
sorry, could you try `npm i -g generator-nativescript-plugin`

**Comment by NickIliev** [comment]
@victorsosa sorry for the typo - this is the command I used initially

**Comment by victorsosa** [comment]
please try `npm i -g typings` and then `npm i -g generator-nativescript-plugin`

**Comment by NickIliev** [comment]
added `typings` however now the creation of plugin (both core or angular2) is failing with

`Cannot read property extend of undefined` at [this line](https://github.com/peoplewareDo/generator-nativescript-plugin/blob/03d167c4845eac233351e555bd28bcc3a566aa92/generators/ng2/index.js#L11)

**Comment by victorsosa** [comment]
I can only think that yeoman is missing

**Comment by briosheje** [comment]
Having the same issue as @NickIliev 

```
Cannot read property 'extend' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-nativescript-plugin/generators/app/index.js:11:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.get [as nativescript-plugin:app] (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:38:27)
    at Store.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:61:39)
```

Yeoman is correctly installed, typings installed as well, generator installation was successful, but running the generator throws this error.
